// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbghklhpxzspqsfnxfux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiZ2hrbGhweHpzcHFzZm54ZnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTQwMTMsImV4cCI6MjA3MzU5MDAxM30.KvxHA8wgImy7x1NBcxKMk6WhIgXEePlcpo8QNNtBFWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});